version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Maintain dependencies for js with npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        versions: ["19.x"]

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "node"
